export const GENERATE_3D = "GENERATE_3D";
export const LOAD_3D = "LOAD_3D";
export const GENERATE_3D_FULFILLED = "GENERATE_3D_FULFILLED";
export const GENERATE_3D_FAILED = "GENERATE_3D_FAILED";
export const GENERATE_3D_CLEARED = "GENERATE_3D_CLEARED";


export const ADD_CALC = "ADD_CALC";
export const ADD_CALC_FULFILLED = "ADD_CALC_FULFILLED";
export const ADD_CALC_FAILED = "ADD_CALC_FAILED";


export const CLEAR_CALC_FULFILLED = "CLEAR_CALC_FULFILLED";
