export const FETCH_CLIENT = "FETCH_CLIENTS";
export const FETCH_CLIENT_FULFILLED = "FETCH_CLIENTS_FULFILLED";
export const FETCH_CLIENT_FAILED = "FETCH_CLIENTS_FAILED";

export const ADD_CLIENT = "ADD_CLIENTS";
export const ADD_CLIENT_FULFILLED = "ADD_CLIENTS_FULFILLED";
export const ADD_CLIENT_FAILED = "ADD_CLIENTS_FAILED";

export const DELETE_CLIENT = "DELETE_CLIENTS";
export const DELETE_CLIENT_FULFILLED = "DELETE_CLIENTS_FULFILLED";
export const DELETE_CLIENT_FAILED = "DELETE_CLIENTS_FAILED";
