export const FETCH_ENTITY = "FETCH_ENTITY";
export const FETCH_ENTITY_FULFILLED = "FETCH_ENTITY_FULFILLED";
export const FETCH_ENTITY_FAILED = "FETCH_ENTITY_FAILED";

export const FETCH_SEARCH_ENTITY = "FETCH_SEARCH_ENTITY";
export const FETCH_SEARCH_ENTITY_FULFILLED="FETCH_SEARCH_ENTITY_FULFILLED";
export const FETCH_SEARCH_ENTITY_FAILED = "FETCH_SEARCH__ENTITY_FAILED";

export const ADD_ENTITY = "ADD_ENTITY";
export const ADD_ENTITY_FULFILLED = "ADD_ENTITY_FULFILLED";
export const ADD_ENTITY_FAILED = "ADD_ENTITY_FAILED";

export const DELETE_ENTITY = "DELETE_ENTITY";
export const DELETE_ENTITY_FULFILLED = "DELETE_ENTITY_FULFILLED";
export const DELETE_ENTITY_FAILED = "DELETE_ENTITY_FAILED";

export const UPDATE_ENTITY = "UPDATE_ENTITY";
export const UPDATE_ENTITY_FULFILLED = "UPDATE_ENTITY_FULFILLED";
export const UPDATE_ENTITY_FAILED = "UPDATE_ENTITY_FAILED";
