export const FETCH_FILE = "FETCH_FILE";
export const FETCH_FILE_FULFILLED = "FETCH_FILE_FULFILLED";
export const FETCH_FILE_FAILED = "FETCH_FILE_FAILED";
export const ADD_DATA_TO_LOM = "ADD_DATA_TO_LOM";
export const DELETE_DATA_FROM_LOM = "DELETE_DATA_FROM_LOM";
export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const RESET_CUSTOMER_DATA = "RESET_CUSTOMER_DATA";