export const OPEN_PROJECT = "OPEN_PROJECT";
export const CLOSE_PROJECT = "CLOSE_PROJECT";
export const SET_PROJECT = "SET_PROJECT";
export const OPEN_TASK = "OPEN_TASK";
export const CLOSE_TASK = "CLOSE_TASK";

export const SHOW_PROJECT_POPUP = "SHOW_PROJECT_POPUP";
export const HIDE_PROJECT_POPUP = "HIDE_PROJECT_POPUP";

export const ENABLE_SKIP_PROJECT_POPUP_CLOSE =
	"ENABLE_SKIP_PROJECT_POPUP_CLOSE";
export const DISABLE_SKIP_PROJECT_POPUP_CLOSE =
	"DISABLE_SKIP_PROJECT_POPUP_CLOSE";

export const FETCH_CLIENT = "FETCH_CLIENT";
export const FETCH_CLIENT_FULFILLED = "FETCH_CLIENT_FULFILLED";
export const FETCH_CLIENT_FAILED = "FETCH_CLIENT_FAILED";

export const ADD_CLIENT = "ADD_CLIENT";
export const ADD_CLIENT_FULFILLED = "ADD_CLIENT_FULFILLED";
export const ADD_CLIENT_FAILED = "ADD_CLIENT_FAILED";

export const DELETE_CLIENT = "DELETE_CLIENT";
export const DELETE_CLIENT_FULFILLED = "DELETE_CLIENT_FULFILLED";
export const DELETE_CLIENT_FAILED = "DELETE_CLIENT_FAILED";
