import * as color from "../variables/color";
export const Fonts = {
	HEADER_NAME: {
		fontSize: "32px",
		lineHeight: "32px",
		fontWeight: "500",
		fontStyle: "normal",
		color: color.brandDarken80,
	},
	H2_BOLD: {
		fontSize: "24px",
		lineHeight: "32px",
		fontStyle: "normal",
		fontWeight: "1000",
		color: color.brandDarken80,
	},
	H2: {
		fontSize: "24px",
		lineHeight: "32px",
		fontStyle: "normal",
		fontWeight: "500",
		color: color.brandDarken80,
	},
	H7: {
		fontSize: "20px",
		lineHeight: "24px",
		fontStyle: "normal",
		fontWeight: "500",
		color: color.brandDarken80,
	},
	H8: {
		fontSize: "18px",
		lineHeight: "24px",
		fontStyle: "normal",
		fontWeight: "500",
		color: color.brandDarken80,
	},
	H9: {
		fontSize: "14px",
		lineHeight: "14px",
		fontStyle: "normal",
		fontWeight: "400",
		color: color.brandDarken80,
	},
	H9_BOLD: {
		fontSize: "14px",
		lineHeight: "20px",
		fontStyle: "normal",
		fontWeight: "500",
		color: color.brandDarken80,
	},
	H11: {
		fontSize: "16px",
		lineHeight: "18px",
		fontStyle: "normal",
		fontWeight: "400",
		color: color.brandDarken80,
	},
	PRE_SELECTED_ITEM: {
		fontSize: "14px",
		lineHeight: "24px",
		fontStyle: "normal",
		fontWeight: "500",
		color: color.brandDarken80,
	},
	SMALL: {
		fontSize: "12px",
		lineHeight: "24px",
		fontStyle: "normal",
		fontWeight: "500",
		color: color.brandDarken80,
	},
	SMALL_LIGHT: {
		fontSize: "12px",
		lineHeight: "24px",
		fontStyle: "normal",
		fontWeight: "400",
		color: color.brandDarken80,
	},
	NUMBER_LARGE: {
		fontSize: "32px",
		lineHeight: "40px",
		fontStyle: "normal",
		fontWeight: "500",
		color: color.brandDarken80,
	},
	ALERT_COUNT: {
		fontSize: "40px",
		lineHeight: "24px",
		fontStyle: "normal",
		fontWeight: "500",
		color: color.brandDarken90,
	},
	SPECIAL_EVENT_SUPPORT_TEXT_1: {
		fontSize: "24px",
		lineHeight: "24px",
		fontStyle: "normal",
		fontWeight: "400",
		color: color.brandDarken90,
		paddingRight: "5px",
	},
};
